INSERT INTO tags (tag_id, tag_name) 
values (default, 'anime'), 
(default, 'food'), 
(default, 'bird'), 
(default, 'star wars'), 
(default, 'building'), 
(default, 'accessory'), 
(default, 'clothing'), 
(default, 'job'), 
(default, 'board game'), 
(default, 'weather'), 
(default, 'monster'), 
(default, 'starter pokemon'), 
(default, 'firearm'), 
(default, 'mammal'), 
(default, 'tv show'), 
(default, 'video game'), 
(default, 'movie');